abstract class AppStates {}
class AppInitialState extends AppStates{}
class AppChangeBottomNavBarState extends AppStates{}
class AppCreateDataBaseState extends AppStates{}
class AppGetDataBaseState extends AppStates{}
class AppGetDataBaseLoadingState extends AppStates{}
class AppInsertToDataBaseState extends AppStates{}
class AppChangeBottomSheetState extends AppStates{}
class AppUpdateDataState extends AppStates{}
class AppDeleteDataState extends AppStates{}